# Generated by Django 6.0.6 on 2026-06-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_vi', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_vnd', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('info_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
