# Generated by Django 6.0.6 on 2026-06-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(verbose_name='Publication Date'),
        ),
    ]
