spring.application.name=HeroGame
server.port=2004

spring.datasource.url=jdbc:mysql://localhost:3306/HeroGame?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Nhật ký hệ thống (Logging)
logging.level.org.hibernate.SQL=DEBUG
